### PR TITLE
Hybridauth 2.13

### PR DESCRIPTION
**Pull request by GunoH**
Upgrade Hybridauth to 2.13 (based on [PR 20](https://github.com/mistic100/Piwigo-Social-Connect/pull/20)).
This fixes [issue 19](https://github.com/mistic100/Piwigo-Social-Connect/issues/19) for me.

### CODE REVIEW

**Comment by GunoH** [comment]
Having some issues still. I'll test some more and reopen when done.

**Comment by GunoH** [comment]
Resolved the issue; turns out Hybridauth did not use the same session as Piwigo did. After disabling the Piwigo session handler (`$conf['session_save_handler'] = '';` in config.inc.php) things were working fine.

**Comment by mistic100** [comment]
> Resolved the issue; turns out Hybridauth did not use the same session as Piwigo did. After disabling the Piwigo session handler (`$conf['session_save_handler'] = '';` in config.inc.php) things were working fine.

Are you saying this is a prerequisite to make the plugin work ? If so then it's a no go of course, the plugin cannot be si tightly dependant of the config.

**Comment by GunoH** [comment]
> the plugin cannot be so tightly dependant of the config.
> Moreover when the default configuration is problematic.

Yeah, I agree. Cannot be merged the way it is now.
Should find a way to make sure the same session is used by both Piwigo and HybridAuth, but I'm not really sure how.

I'll close this one for now.
If anyone's got any tips on how to proceed, please let me know (though I'm not planning to invest a lot of time in this issue).

**Comment by kchen** [comment]
I upgraded to Hybridauth 2.17 and made no other changes to Piwigo or Social Connect, and that appears to resolve the problem for me.

**Pull request closed without merging**
